### ISSUE TITLE
NameError: uninitialized constant ActiveRecord::Tasks::DatabaseTasks::Rails

### ISSUE THREAD

**Issue by junsumida** [mixi-inc/RubyTraining#70]
```
NameError: uninitialized constant ActiveRecord::Tasks::DatabaseTasks::Rails
/Users/jun.sumida/.rvm/gems/ruby-2.1.0/gems/activerecord-4.1.0/lib/active_record/tasks/database_tasks.rb:54:in `db_dir'
/Users/jun.sumida/.rvm/gems/ruby-2.1.0/gems/sinatra-activerecord-1.7.0/lib/sinatra/activerecord/rake.rb:112:in `db_dir'
/Users/jun.sumida/.rvm/gems/ruby-2.1.0/gems/sinatra-activerecord-1.7.0/lib/sinatra/activerecord/rake.rb:67:in `dump_schema'
/Users/jun.sumida/.rvm/gems/ruby-2.1.0/gems/sinatra-activerecord-1.7.0/lib/sinatra/activerecord/tasks.rake:58:in `block (3 levels) in <top (required)>'
/Users/jun.sumida/.rvm/gems/ruby-2.1.0/gems/sinatra-activerecord-1.7.0/lib/sinatra/activerecord/tasks.rake:34:in `block (2 levels) in <top (required)>'
/Users/jun.sumida/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
/Users/jun.sumida/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:schema:dump
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [rake db:migrate...]
/Users/jun.sumida/github/mosscow/Rakefile:13:in `block in <top (required)>'
/Users/jun.sumida/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
/Users/jun.sumida/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
```

sinatra-activerecordのバグっぽい。

**Comment by junsumida** [comment]
3f121caf01197f1370b3c28cd2495388aeee4964 で`problems`は対応した.
#69 で`master`も対応済
